site_name: RevoltDocs
site_url: https://ricky074game.github.io/RevoltDocs/

theme:
  name: material
  palette:
    - scheme: slate
      primary: black
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: white
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.path
    - navigation.prune
    - search.highlight
    - search.share
  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/ricky074game/RevoltUltimate
repo_name: ricky074game/RevoltUltimate

nav:
  - Home: index.md
  - Setup: setup.md
  - Achievements:
      - Getting Started:  achievements/achievements.md
      - Steam:
          - SteamScrape: achievements/Steam/SteamScrape.md
          - SteamAPI: achievements/Steam/SteamAPI.md
      - Pirated Steam:
          - Inside Game Folder: achievements/Steam/InsideGameFolder.md
          - Outside Game Folder: achievements/Steam/OutsideGameFolder.md
      - GOG:
          - CometOffline: achievements/GOG/CometOffline.md
          - Comet Normal: achievements/GOG/Comet.md
          - GOG Scrape: achievements/GOG/GOGScrape.md
  - FAQ: faq.md
  - Development: development.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - styles.css
